baseURL = "http://example.com"
languageCode = "en-us"
title = "Example Site"

theme = ""
googleAnalytics = ""

enableEmoji = true

[blackfriday]
	hrefTargetBlank	=	true

[params]
description = "This is the description of my example site."


[social]
	twitter = ""

[[menu.main]]
	name	= "Home"
	url		= "/"
	weight	= -1
